# Generated by Django 5.0.14 on 2025-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
    ]
